# Generated by Django 4.2.20 on 2025-04-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类')], verbose_name='Job type')),
                ('job_name', models.CharField(max_length=255, verbose_name='Job name')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '深圳'), (2, '上海')], verbose_name='Job city')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='Job responsibility')),
                ('job_requirements', models.TextField(max_length=1024, verbose_name='Job requirements')),
                ('created_date', models.DateTimeField(verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modified date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
